title: Pedro Simões
description: > # this means to ignore newlines until "baseurl:"
  Pedro Simões is a weirdo from Costa da Caparica Portugal. Curious about all things. In love with software and giving its best @Worten
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://psimoesSsimoes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/seomisw" #if your site has a twitter account, enter it here

# Author Settings
author: Pedro Simões # add your name
author-img: simoes.jpg # add your photo
about-author: Simply following my passions. I try to make a difference, so i do my best every day.
social-twitter: seomisw # add your Twitter handle
social-github: psimoesSsimoes # ig handle
social-linkedin: pedro-simões # add your Linkedin handle
social-email: seomisw@gmail.com # add your Email address

# Disqus
discus-identifier: Pedro Simões # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
